version: '3.7'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: dockette/adminer
    restart: always
    ports:
      - 8080:80
